const $=s=>document.querySelector(s);
function getCart(){return JSON.parse(localStorage.getItem("booknook_cart")||"[]")}
function saveCart(c){localStorage.setItem("booknook_cart",JSON.stringify(c));updateCartCount()}
function updateCartCount(){const n=getCart().reduce((a,x)=>a+x.qty,0);document.querySelectorAll("#cartCount").forEach(e=>e.textContent=n)}
function addToCart(id){let c=getCart(),item=c.find(x=>x.id==id);if(item)item.qty++;else c.push({id,qty:1});saveCart(c);toast("Added to your cart ✓")}
function toast(t){let x=document.createElement("div");x.textContent=t;x.style.cssText="position:fixed;bottom:25px;right:25px;background:#2D6A4F;color:white;padding:12px 18px;border-radius:8px;z-index:99;box-shadow:0 10px 25px #0002";document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
function toggleSearch(){$("#searchBar")?.classList.toggle("hidden");$("#searchInput")?.focus()}
function cardHTML(b){return `<article class="product-card"><a href="product.html?id=${b.id}"><div class="cover"><div class="cover-inner" style="background:${b.color}"><span class="cover-title">${b.title}</span><small>${b.author}</small></div></div></a><div class="product-info"><span class="author">${b.category} · ${b.sub}</span><h3><a href="product.html?id=${b.id}">${b.title}</a></h3><span class="rating">★ ${b.rating} (${b.reviews})</span><div class="card-row"><span class="price">₹${b.price}</span><button class="add" onclick="addToCart(${b.id})">Add</button></div></div></article>`}
function renderHome(){let el=$("#homeProducts");if(el)el.innerHTML=books.slice(0,4).map(cardHTML).join("")}
function renderProducts(){let grid=$("#productGrid");if(!grid)return;let q=($("#q")?.value||"").toLowerCase(),cat=$("#category")?.value||new URLSearchParams(location.search).get("category")||"",lang=$("#language")?.value||"",max=+($("#price")?.value||1500),rate=+($("#rating")?.value||0);if($("#category")&&new URLSearchParams(location.search).get("category")&&!$("#category").value)$("#category").value=cat;let arr=books.filter(b=>(!q||(b.title+" "+b.author).toLowerCase().includes(q))&&(!cat||b.category==cat)&&(!lang||b.language==lang)&&b.price<=max&&b.rating>=rate);let sort=$("#sort")?.value;if(sort=="low")arr.sort((a,b)=>a.price-b.price);if(sort=="high")arr.sort((a,b)=>b.price-a.price);if(sort=="rating")arr.sort((a,b)=>b.rating-a.rating);grid.innerHTML=arr.length?arr.map(cardHTML).join(""):`<div class="empty"><h2>No matches found</h2><p>Try changing your filters.</p></div>`;if($("#resultCount"))$("#resultCount").textContent=`${arr.length} items`;if($("#priceVal"))$("#priceVal").textContent="₹"+max}
function clearFilters(){["q","category","language"].forEach(id=>{if($("#"+id))$("#"+id).value=""});if($("#price"))$("#price").value=1500;if($("#rating"))$("#rating").value=0;renderProducts()}
function searchHome(){let q=$("#searchInput")?.value.trim();if(q){location.href="products.html?q="+encodeURIComponent(q)}}
function renderDetail(){let el=$("#detail");if(!el)return;let id=+new URLSearchParams(location.search).get("id"),b=books.find(x=>x.id==id)||books[0];el.innerHTML=`<div class="detail-wrap"><div class="detail-cover"><div class="cover-inner" style="background:${b.color}"><span class="cover-title">${b.title}</span><small>${b.author}</small></div></div><div><p class="eyebrow">${b.category} · ${b.sub}</p><h1>${b.title}</h1><p class="author">by ${b.author} · ★ ${b.rating} (${b.reviews} reviews)</p><p class="desc">${b.desc}</p><div class="meta"><div><b>Publisher</b><br>${b.publisher}</div><div><b>ISBN</b><br>${b.isbn}</div><div><b>Language</b><br>${b.language}</div><div><b>Format</b><br>Paperback</div></div><div class="price">₹${b.price}</div><div class="qty"><button onclick="changeDetailQty(-1)">−</button><span id="dq">1</span><button onclick="changeDetailQty(1)">+</button></div><button class="btn" onclick="addDetail(${b.id})">Add to cart</button></div></div>`}
let detailQty=1;function changeDetailQty(n){detailQty=Math.max(1,detailQty+n);$("#dq").textContent=detailQty}function addDetail(id){let c=getCart(),i=c.find(x=>x.id==id);if(i)i.qty+=detailQty;else c.push({id,qty:detailQty});saveCart(c);toast("Added to your cart ✓")}
function renderCart(){let el=$("#cartContent");if(!el)return;let c=getCart();if(!c.length){el.innerHTML=`<div class="empty"><h2>Your cart is waiting for a good story.</h2><p>Add a few favorites and they'll appear here.</p><a class="btn" href="products.html">Browse books</a></div>`;return}let total=0;let rows=c.map(x=>{let b=books.find(y=>y.id==x.id);total+=b.price*x.qty;return `<div class="cart-item"><div class="mini-cover"><div class="cover-inner" style="background:${b.color}"><span class="cover-title">${b.title}</span></div></div><div><h3>${b.title}</h3><p class="muted">${b.author} · ₹${b.price}</p><div class="qty"><button onclick="updateQty(${b.id},-1)">−</button><span>${x.qty}</span><button onclick="updateQty(${b.id},1)">+</button><button class="add" onclick="removeItem(${b.id})">Remove</button></div></div><b>₹${b.price*x.qty}</b></div>`}).join("");el.innerHTML=`<div class="cart-layout"><div>${rows}</div><aside class="summary card"><h2>Order summary</h2><div class="summary-row"><span>Subtotal</span><b>₹${total}</b></div><div class="summary-row"><span>Delivery</span><b>${total>=499?"FREE":"₹49"}</b></div><div class="summary-row total"><span>Total</span><span>₹${total+(total>=499?0:49)}</span></div><a class="btn full-btn" href="checkout.html">Proceed to checkout</a></aside></div>`}
function updateQty(id,n){let c=getCart(),i=c.find(x=>x.id==id);if(i){i.qty+=n;if(i.qty<=0)c=c.filter(x=>x.id!=id)}saveCart(c);renderCart()}
function removeItem(id){saveCart(getCart().filter(x=>x.id!=id));renderCart()}
function renderCheckout(){let el=$("#checkoutSummary");if(!el)return;let c=getCart();if(!c.length){el.innerHTML="<h2>Cart is empty</h2><a class='btn' href='products.html'>Shop now</a>";return}let total=0;el.innerHTML="<h2>Order summary</h2>"+c.map(x=>{let b=books.find(y=>y.id==x.id);total+=b.price*x.qty;return `<div class="checkout-summary-item"><span>${b.title} × ${x.qty}</span><b>₹${b.price*x.qty}</b></div>`}).join("")+`<div class="summary-row total"><span>Total</span><b>₹${total+(total>=499?0:49)}</b></div>`}
function placeOrder(e){e.preventDefault();if(!getCart().length){alert("Your cart is empty.");return}let order={date:new Date().toLocaleDateString(),items:getCart(),name:$("#name").value};localStorage.setItem("booknook_last_order",JSON.stringify(order));saveCart([]);document.body.innerHTML=`<main class="auth"><div class="auth-box card" style="text-align:center"><div style="font-size:50px">✓</div><p class="eyebrow">Order confirmed</p><h1>Thank you, ${order.name}!</h1><p>Your demo order has been placed successfully. Order tracking is simulated.</p><a class="btn" href="index.html">Back to BookNook</a></div></main>`}
function login(e){e.preventDefault();alert("Demo login successful!");location.href="account.html"}function register(e){e.preventDefault();alert("Demo account created!");location.href="account.html"}function contactSubmit(e){e.preventDefault();alert("Thanks! Your message has been received in this demo.");e.target.reset()}
document.addEventListener("DOMContentLoaded",()=>{updateCartCount();renderHome();renderProducts();renderDetail();renderCart();renderCheckout();$("#checkoutForm")?.addEventListener("submit",placeOrder);["q","category","language","price","rating","sort"].forEach(id=>$("#"+id)?.addEventListener("input",renderProducts));let qp=new URLSearchParams(location.search).get("q");if(qp&&$("#q")){$("#q").value=qp;renderProducts()}});
