const books=[
{id:1,title:"The Midnight Library",author:"Matt Haig",category:"Fiction",sub:"Literary Fiction",language:"English",price:499,rating:4.7,reviews:182,publisher:"Canongate",isbn:"9780525559474",color:"#315c4c",desc:"Between life and death there is a library. When Nora Seed finds herself there, she discovers the countless lives she might have lived."},
{id:2,title:"Atomic Habits",author:"James Clear",category:"Non-Fiction",sub:"Self-Help",language:"English",price:599,rating:4.8,reviews:310,publisher:"Avery",isbn:"9780735211292",color:"#233f63",desc:"An easy and proven way to build good habits, break bad ones, and master the tiny behaviors that lead to remarkable results."},
{id:3,title:"The Alchemist",author:"Paulo Coelho",category:"Fiction",sub:"Literary Fiction",language:"English",price:399,rating:4.6,reviews:265,color:"#a87532",publisher:"HarperOne",isbn:"9780062315007",desc:"A shepherd boy travels from Spain to the Egyptian pyramids in search of a treasure and discovers a deeper meaning along the way."},
{id:4,title:"Ikigai",author:"Héctor García",category:"Non-Fiction",sub:"Self-Help",language:"English",price:449,rating:4.5,reviews:147,color:"#7d4e4e",publisher:"Penguin Life",isbn:"9780143130727",desc:"A gentle exploration of the Japanese concept of ikigai—the intersection of what you love, what you are good at, and what the world needs."},
{id:5,title:"The Hobbit",author:"J.R.R. Tolkien",category:"Fiction",sub:"Fantasy",language:"English",price:699,rating:4.9,reviews:420,color:"#536a39",publisher:"HarperCollins",isbn:"9780261102217",desc:"Bilbo Baggins is swept into an unexpected adventure with dwarves, dragons and a journey across Middle-earth."},
{id:6,title:"Wings of Fire",author:"A.P.J. Abdul Kalam",category:"Non-Fiction",sub:"Biography",language:"English",price:350,rating:4.7,reviews:290,color:"#805c3c",publisher:"Universities Press",isbn:"9788173711466",desc:"The inspiring autobiography of India's former President, tracing his journey from a small-town childhood to the world of science."},
{id:7,title:"Grandma's Bag of Stories",author:"Sudha Murty",category:"Children",sub:"Story Books",language:"English",price:299,rating:4.8,reviews:156,color:"#d17858",publisher:"Penguin",isbn:"9780143440054",desc:"A warm collection of stories told by a grandmother to her grandchildren, filled with wit, wisdom and wonder."},
{id:8,title:"The Very Hungry Caterpillar",author:"Eric Carle",category:"Children",sub:"Picture Books",language:"English",price:275,rating:4.9,reviews:380,color:"#bd493f",publisher:"World of Eric Carle",isbn:"9780241003008",desc:"A tiny caterpillar eats his way through a week of delicious treats before transforming into a beautiful butterfly."},
{id:9,title:"Think Like a Monk",author:"Jay Shetty",category:"Non-Fiction",sub:"Self-Help",language:"English",price:549,rating:4.4,reviews:121,color:"#4f5c70",publisher:"HarperCollins",isbn:"9781982134488",desc:"Practical wisdom and exercises inspired by monk training to help cultivate purpose, focus, discipline and compassion."},
{id:10,title:"Kadal Pura",author:"Sandilyan",category:"Fiction",sub:"Historical Fiction",language:"Tamil",price:420,rating:4.6,reviews:88,color:"#496d78",publisher:"Vanathi",isbn:"9788190000001",desc:"A classic Tamil historical adventure filled with romance, naval journeys, intrigue and the vivid world of the Chola era."},
{id:11,title:"Classic Journal",author:"BookNook Studio",category:"Stationery",sub:"Notebooks & Journals",language:"English",price:199,rating:4.5,reviews:72,color:"#6c7b59",publisher:"BookNook",isbn:"STN-001",desc:"A sturdy lined journal with a warm paper feel—ideal for reading notes, study plans and everyday thoughts."},
{id:12,title:"Scholar Pen Set",author:"BookNook Studio",category:"Stationery",sub:"Pens & Pencils",language:"English",price:149,rating:4.3,reviews:55,color:"#5c6a76",publisher:"BookNook",isbn:"STN-002",desc:"A simple set of smooth-writing pens designed for study desks, notebooks and long reading sessions."}
];